version: '3.9'

services:
    app:
        build: .
        container_name: app
        ports:
            - "81:80"
    cache:
        image: redis:latest
        container_name: cache
        ports:
            - "6380:6379"
    queue:
        image: rabbitmq:3-management
        container_name: queue
        ports:
            - "5672:5672"
            - "15672:15672"
